<?php
return [
    'intertexts' => [
        'introduction_general' => 'intro_tuk',
        'original_info' => 'tooltip_tuk_originalsprache',
        'transcription_info' => 'tooltip_tuk_originalsprache_transkription',
        'source_info' => 'tooltip_tuk_identifizierung',
        'commentary_info' => 'tooltip_tuk_kommentarreferenz',
        'how_to_cite' => 'editorinfo_kontexte',
        'arabic_text_info' => 'headline_arabic',
        'translation_info' => 'headline_translation',
    ],
    'print-edition' => [
        'introduction_general' => 'einleitung_index',
        'arabic_text_info' => 'headline_arabic',
        'transcription_info' => 'label_transkription_tooltip',
        'translation_info' => 'headline_translation',
        'image_description_short' => 'label_abbild_beschreibung',
        'image_description_long' => 'label_abbild',
        'how_to_cite' => 'editorinfo_print_edition',
        'morphology_info' => 'druckausgabe.infotext.morphologische_analyse',
    ],
    'concordance' => [
        'analysis_info' => 'concordance_analysis_rafi_talmon',
        'talmon_info' => 'concordance_info_rafi_talmon',
        'transcription_info' => 'label_transkription_tooltip',
        'arabic_text_info' => 'headline_arabic',
        'how_to_cite' => 'editorinfo_concordance',
    ],
    'manuscripts' => [
        'how_to_cite' => 'editorinfo_handschriften',
        'introduction' => 'intro-manuscripta',
        'arabic_text_info' => 'headline_arabic',
        'transcription_info' => 'label_transkription_tooltip',
        'translation_info' => 'headline_translation',
        'transliteration_info' => 'handschriften_label_transliteration_tooltip',
        'infotext' => 'infotext_handschriften',
        // 'choose_image' =>  'handschriften_bildauswahl',
        // 'no_transliteration' => 'handschriften_keine_transliteration',
        // 'current_manuscript_page' => 'manuscript_page_shown',
        // 'text_passage_quram' => 'handschriften_label_textstelle',
        // 'folio_page' =>  'manuskriptseiten_label_folioundseite',
        // 'reference' =>  'manuskript_nachweis',
        // 'unknown_extent' => 'unbekannter_umfang',
        // 'unknown_format' => 'unbekanntest_format',
        // 'unknown_date' => 'unbekannte_datierung',
        // 'unknown_condition' => 'unbekannter_zustand',
        // 'unknown_depository' => 'unbekannter_ort',
        // 'unknown_segment' => 'unbekannter_abschnitt',
        // 'unknown_linenumbers' => 'unbekannte_zeilenzahl',
        // 'tooltip_transliteration' => 'handschriften_label_transliteration_tooltip',
        // 'introduction_manuscript_text' => 'einleitung_handschriften',
        // 'introduction_example_title' => 'handschriften_beispiele_titel',
        // 'introduction_examples_text' => 'handschriften_beispiele_description',
        // 'introduction_example1' => 'handschriften_beispiel_1',
        // 'introduction_example2' => 'handschriften_beispiel_2',
        // 'introduction_example3' => 'handschriften_beispiel_3',
    ],
    'variants' => [
        'how_to_cite' => 'editorinfo_lesarten',
        'arabic_text_info' => 'headline_arabic',
        'transcription_info' => 'label_transkription_tooltip',
        'infotext' => 'infotext_lesarten',
    ],
    'commentary' => [
        'infotext' => 'infotext_kommentar',
    ],
];
