services:
  frontend:
    build:
      context: frontend
      args:
        # For the frontend local nginx config.
        LOCALHOST: "true"
        VUE_APP_BACKEND_URL: http://localhost:26728
    ports:
      - 8080:80
    restart: always
  nginx_backend:
    build:
      context: backend
      dockerfile: nginx.Dockerfile
    ports:
      - 26728:80
  php_backend:
    build:
      context: backend
      dockerfile: php.Dockerfile
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: "http://localhost:26728"
      LOG_LEVEL: debug
      XML_FILES_FOLDER: "./corpus_coranicum_xml_files"
      DB_CONNECTION: mysql
      DB_HOST: db 
      DB_PORT: 3306
      DB_DATABASE: corpuscoranicum
      DB_USERNAME: user
      DB_PASSWORD: password
    volumes:
      - ../corpus_coranicum_xml_files:/backend/corpus_coranicum_xml_files
  db:
    image: mysql:5.7.37
    ports:
      - 3005:3306
    cap_add:
      # https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log
      - SYS_NICE
    command: --max_allowed_packet=32505856 # Set max_allowed_packet to 256M (or any other value)
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: corpuscoranicum
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
